use DbDISUCII

SELECT 
DETOPE.PROCOD, 
DETOPE.ASOCOD, 
DETOPE.DETMED, 
DETOPE.DETDSC, 
CONVERT(varchar, DETOPE.DETFVE, 121) as FechaVencimiento,
DETOPE.DETLOT, 
MAEASO.ASOCOD, 
maeaso.ASONRZ,
count(DETOPE.detcod) as Cant,
vintxp.TXTSTK as Stock,
sum(DETOPE.DETSTK) as SumStock
FROM            MAEPRO INNER JOIN
                         MAEASO ON MAEASO.ASOCOD = MAEPRO.ASOCOD INNER JOIN
                         VINTXP ON MAEPRO.PROCOD = VINTXP.PROCOD INNER JOIN
                         DETOPE ON VINTXP.PROCOD = DETOPE.PROCOD AND VINTXP.ASOCOD = DETOPE.ASOCOD INNER JOIN
                         MAEOPE ON DETOPE.OPECOD = MAEOPE.OPECOD AND DETOPE.EJECOD = MAEOPE.EJECOD AND DETOPE.MAE_ASOCOD = MAEOPE.MAE_ASOCOD AND DETOPE.DOCCOD = MAEOPE.DOCCOD AND
						 DETOPE.CTACOD = MAEOPE.CTACOD
						 where DETOPE.ASOCOD = 'DISUC' and DETOPE.DETSTK > 0 and MAEOPE.OPEANU = 0
-- and detope.PROCOD = 'LB00760002'
group by DETOPE.PROCOD, 
DETOPE.ASOCOD, 
DETOPE.DETMED, 
DETOPE.DETDSC, 
DETOPE.DETPREC,  
CONVERT(varchar, DETOPE.DETFVE, 121),
DETOPE.DETLOT, 
MAEASO.ASOCOD, 
maeaso.ASONRZ,
vintxp.TXTSTK
ORDER BY MAEASO.ASONRZ, DETOPE.DETDSC
